config/routes.rb
Rails.application.routes.draw do  
  root 'music_albums#index'
  resources :music_albums
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music_album.rb
class MusicAlbum < ApplicationRecord
 has_one_attached :cover_image
 has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/music_albums_controller.rb
class MusicAlbumsController < ApplicationController
  def index
    @musicalbums=MusicAlbum.all
  end

   #  def all_albums
  #   @albums = Album.where(published: true)
  #   @album = Album.where(published: true).count
  #   @user = User.all
  # end

  # def draft_album
  #   @albums = current_user.albums.where(published: false)
  #   @album_draft = current_user.albums.where(published: false).count
  # end

  # def published_album
  #   @albums = current_user.albums.where(published: true)
  #   @album = current_user.albums.where(published: true).count
  # end

  def show
    @musicalbum= MusicAlbum.find(params[:id])
  end

  def new

    @musicalbum= MusicAlbum.new
  end

  def create
    @musicalbum = MusicAlbum.new(musicalbum_params)

    if @musicalbum.save
      redirect_to @musicalbum
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @musicalbum = MusicAlbum.find(params[:id])
  end

  def update
    @musicalbum = MusicAlbum.find(params[:id])

    if @musicalbum.update(musicalbum_params)
      redirect_to @musicalbum
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @musicalbum= MusicAlbum.find(params[:id])
    @musicalbum.destroy

    redirect_to root_path
  end

  # def delete_image
  #   attachment = ActiveStorage::Attachment.find(params[:id])
  #   attachment.purge # or use purge_later
  #   redirect_back(fallback_location: albums_url)
  # end

  private

  def musicalbum_params
    params.require(:music_album).permit(:name, :description, :price, :cover_image, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/music_albums_helper.rb
module MusicAlbumsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
 
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/music_albums/_form.html.erb
<%=form_with  model: musicalbum do |form|%> 
<% if musicalbum.errors.full_messages.any? %>
<% musicalbum.errors.full_messages.each do |error_message| %> 
<%= error_message if musicalbum.errors.full_messages.first == error_message %> <br />
<% end %> 
<% end %>
<div>
  <%=form.label :name%> 
  <%=form.text_field :name, class:'form-control'%>
</div>
<br />
 <div>
  <%=form.label :cover_image%> 
  <%=form.file_field:cover_image,class:'form-control'%>
</div> 
<br />
<div>
  <%=form.label :description%> 
  <%=form.text_area:description, class:'form-control'%>
</div>
<br />
 <div>
  <%=form.label :music_file%> 
  <%=form.file_field:file,class:'form-control'%>
</div> 
<br />

<br />
<div>
  <%=form.label :price%> 
  <%=form.text_field:price, class:'form-control'%>
</div>
<br />
<div><%=form.submit%></div>
<%end%>
<br />

app/views/music_albums/edit.html.erb
<h1>Edit Music Album</h1>

<%= render "form", musicalbum: @musicalbum%> 
<%=link_to "Back" , root_path, class:'btn btn-secondary'%>

app/views/music_albums/index.html.erb
<div class="row">
  <% @musicalbums.each do |album| %>
    <div class="col-md-4">
      <div class="card">
      	 <div class="card-header">
          <%= link_to music_album_path(album),method: :delete, data: { confirm: "Are you sure?" } do   %>
            <i class="fas fa-times right"></i>
          <%end %>
          <%= link_to edit_music_album_path(album)do   %>
            <i class="fas fa-edit green"></i>
          <%end %>
        </div>
        <div class="card-body">
          <% if album.cover_image.attached? %>
            <%= link_to album,class:"link" do%>
              <%=image_tag(album.cover_image,class: "card-top-img img-fluid") %>
            <%end%> <%end%>
        </div>

          <div class="card-footer">
            <span>
              <strong>Name:</strong>
              <%=album.name%>
            </span>
            <span class="pl">
              <strong>Description:</strong>
              <%=album.description%>
            </span>
          </div>
          <div class="card-footer">
            <span>
              <strong>Price:</strong>	
              <%= album.price%>
            </span>
          </div>

      </div>
    </div>
  <%end%>
</div>
<%=link_to "New Music Album", new_music_album_path%>

app/views/music_albums/new.html.erb
<h1>New Music Album</h1>

<%= render "form", musicalbum: @musicalbum%>

app/views/music_albums/show.html.erb
<h1>Album</h1>
<p id="notice"><%= notice%></p>
<div class="col-md-12">
  <div class="card">
    <div class="card-body">
      <% if @musicalbum.cover_image.attached? %>
        <%=image_tag(@musicalbum.cover_image,class: "card-top-img img-fluid") %>
      <%end%>
    </div>
      <div class="card-footer">
        <span>
          <strong>Title:</strong>
          <%=@musicalbum.name%>
        </span>
        <span class="pl">
          <strong>Description:</strong>
          <%=@musicalbum.description%>
        </span>
      </div>
      <div class="card-footer">
        <span>
          <strong>Price:</strong>
          <%=@musicalbum.price %>
        </span>
      </div>

<div class="card-footer text-center">
  <% if @musicalbum.file.attached? %>
    <audio controls>
      <source src="<%= rails_blob_url (@musicalbum.file) %>" type="<%=@musicalbum.file.content_type%>"/>
    </audio>
  <%end%>
</div>      
</div>